[versions]
lombok = "1.18.42"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
mojang-dfu = { module = "com.mojang:datafixerupper", version = "8.0.16" }
mojang-brigadier = { module = "com.mojang:brigadier", version = "1.3.10" }
